---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: demo
        image: public.ecr.aws/p2j8v6t3/demo-poc:latest
        ports:
        - containerPort: 3000
...
